---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure CRI-O's version of runc is installed on Debian/Ubuntu hosts.
  package:
    name: "cri-o-runc"
    state: "{{ crio_package_state }}"
  when: ansible_os_family == 'Debian'

- name: Install kubernetes-cni
  package:
    name: "kubernetes-cni"
    state: "{{ crio_package_state }}"

- name: Ensure CRI-O is installed.
  package:
    name: "{{ crio_package }}"
    state: "{{ crio_package_state }}"

- name: Ensure CRI-O is started and enabled at boot.
  service:
    name: crio
    state: "{{ crio_service_state }}"
    enabled: "{{ crio_service_enabled }}"
