---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure CRI-O's version of runc is installed on Debian/Ubuntu hosts.
  package:
    name: "cri-o-runc"
    state: "{{ crio_package_state }}"
  when:
    - ansible_os_family == 'Debian'
    - crio_runtime == 'runc'

- name: Install crun
  package:
    name: "crun"
    state: "{{ crio_package_state }}"
  when: crio_runtime == 'crun'

- name: Configure CRI-O to use crun
  copy:
    src: "crun.conf"
    dest: "/etc/crio/crio.conf.d/99-crun.conf"
    owner: root
    group: root
    mode: 0644

- name: Install kubernetes-cni
  package:
    name: "kubernetes-cni"
    state: "{{ crio_package_state }}"

- name: Install containers-common
  package:
    name: "containers-common"
    state: "{{ crio_package_state }}"

- name: Set the CRI-O storage driver
  lineinfile:
    path: "/etc/containers/storage.conf"
    regexp: '^driver\s*='
    line: 'driver = "{{ crio_storage_driver }}"'
    owner: root
    group: root
    mode: 0644

- name: Ensure CRI-O is installed.
  package:
    name: "{{ crio_package }}"
    state: "{{ crio_package_state }}"

- name: Ensure CRI-O is started and enabled at boot.
  service:
    name: crio
    state: "{{ crio_service_state }}"
    enabled: "{{ crio_service_enabled }}"
