---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - curl
    state: present

- name: Include OS-specific variables
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: Download the Kubic project apt key
  get_url:
    url: "{{ kubic_apt_gpg_key }}"
    dest: "{{ kubic_apt_gpg_key_local_path }}"
    owner: root
    group: root
    mode: 0644

- name: Add Kubic project repository.
  apt_repository:
    repo: "{{ kubic_apt_repository }}"
    filename: "devel:kubic:libcontainers:stable"
    state: present
    update_cache: true

- name: Add CRI-O repository.
  apt_repository:
    repo: "{{ crio_apt_repository }}"
    filename: "devel:kubic:libcontainers:stable:cri-o"
    state: present
    update_cache: true

- name: Download the Kubernetes apt key
  get_url:
    url: "{{ kubernetes_apt_gpg_key }}"
    dest: "{{ kubernetes_apt_gpg_key_local_path }}"
    owner: root
    group: root
    mode: 0644

- name: Add Kubernetes repository.
  apt_repository:
    repo: "{{ kubernetes_apt_repository }}"
    state: present
    update_cache: true
